In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_excel(r'D:\123\dse\iris.xls')

In [3]:
data.head(10)

SL   SW   PL   PW Classification
0  5.1  3.5  1.4  0.2    Iris-setosa
1  4.9  3.0  1.4  0.2    Iris-setosa
2  NaN  3.2  1.3  0.2    Iris-setosa
3  4.6  3.1  1.5  0.2    Iris-setosa
4  5.0  3.6  1.4  0.2    Iris-setosa
5  5.4  3.9  1.7  0.4    Iris-setosa
6  4.6  3.4  1.4  0.3    Iris-setosa
7  5.0  3.4  1.5  0.2    Iris-setosa
8  4.4  2.9  1.4  0.2    Iris-setosa
9  4.9  3.1  1.5  0.1    Iris-setosa

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   SL              143 non-null    float64
 1   SW              144 non-null    float64
 2   PL              144 non-null    float64
 3   PW              150 non-null    float64
 4   Classification  150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [5]:
data['SL'].unique()

array([5.1, 4.9, nan, 4.6, 5. , 5.4, 4.4, 4.8, 4.3, 5.8, 5.7, 5.2, 4.7,
       5.5, 4.5, 5.3, 7. , 6.9, 6.5, 6.3, 6.6, 5.9, 6. , 6.1, 5.6, 6.7,
       6.2, 6.4, 6.8, 7.1, 7.6, 7.3, 7.2, 7.7, 7.4, 7.9])

In [6]:
data['SW'].unique()

array([3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 2.9, nan, 4. , 4.4, 3.8, 3.7,
       3.3, 4.1, 4.2, 2.3, 2.8, 2.4, 2.7, 2. , 2.2, 2.5, 2.6])

In [7]:
data['PL'].unique()

array([1.4, 1.3, 1.5, 1.7, 1.6, 1.1, 1.2, 1. , 1.9, nan, 4.7, 4.5, 4.9,
       4. , 4.6, 3.3, 3.9, 3.5, 4.2, 3.6, 4.4, 4.1, 4.8, 4.3, 5. , 3.8,
       3.7, 5.1, 3. , 6. , 5.9, 5.6, 5.8, 6.6, 6.3, 5.3, 5.5, 6.7, 6.9,
       5.7, 6.1, 6.4, 5.4, 5.2])

In [8]:
data['PW'].unique()

array([0.2, 0.4, 0.3, 0.1, 0.5, 0.6, 1.4, 1.5, 1.3, 1.6, 1. , 1.1, 1.8,
       1.2, 1.7, 2.5, 1.9, 2.1, 2.2, 2. , 2.4, 2.3])

# drop non value column

In [9]:
data = data.dropna()

# covert non integer to integer

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['Classification'] = le.fit_transform(data['Classification'])

In [11]:
data

SL   SW   PL   PW  Classification
0    5.1  3.5  1.4  0.2               0
1    4.9  3.0  1.4  0.2               0
3    4.6  3.1  1.5  0.2               0
4    5.0  3.6  1.4  0.2               0
5    5.4  3.9  1.7  0.4               0
..   ...  ...  ...  ...             ...
144  6.7  3.3  5.7  2.5               2
145  6.7  3.0  5.2  2.3               2
146  6.3  2.5  5.0  1.9               2
148  6.2  3.4  5.4  2.3               2
149  5.9  3.0  5.1  1.8               2

[131 rows x 5 columns]

# data spliting

In [12]:
y = data['Classification']
x = data.drop(['Classification'],axis=1)

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=42)

# SVM

In [14]:
from sklearn.svm import SVC
svmclf = SVC(kernel = 'linear')
svmclf.fit(x_train,y_train)

SVC(kernel='linear')

In [15]:
y_pred_svm = svmclf.predict(x_test)

In [16]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [17]:
print('accuracy =' , accuracy_score(y_test,y_pred_svm))

accuracy = 1.0


In [18]:
print(confusion_matrix(y_test,y_pred_svm))

[[12  0  0]
 [ 0 13  0]
 [ 0  0  8]]


# using different kernel RBF

In [19]:
from sklearn.svm import SVC
svmclf = SVC(kernel = 'rbf')
svmclf.fit(x_train,y_train)

SVC()

In [20]:
y_pred_svm = svmclf.predict(x_test)

In [21]:
print('accuracy =' , accuracy_score(y_test,y_pred_svm))

accuracy = 1.0


# using different kernel Polinomial

In [22]:
from sklearn.svm import SVC
svmclf = SVC(kernel = 'poly')
svmclf.fit(x_train,y_train)

SVC(kernel='poly')

In [23]:
y_pred_svm = svmclf.predict(x_test)

In [24]:
print('accuracy =' , accuracy_score(y_test,y_pred_svm))

accuracy = 1.0


# Decision tree

In [25]:
from sklearn.tree import DecisionTreeClassifier
dt_clf = DecisionTreeClassifier()
dt_clf.fit(x_train,y_train)

DecisionTreeClassifier()

In [26]:
y_pred_dt = dt_clf.predict(x_test)

In [27]:
print('accuracy =' , accuracy_score(y_test,y_pred_dt))

accuracy = 1.0


In [28]:
print(confusion_matrix(y_test,y_pred_dt))

[[12  0  0]
 [ 0 13  0]
 [ 0  0  8]]


# RANDOM FOREST

In [29]:
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier()
rf_clf.fit(x_train,y_train)

RandomForestClassifier()

In [30]:
y_pred_rf = rf_clf.predict(x_test)

In [31]:
print('accuracy =' , accuracy_score(y_test,y_pred_rf))

accuracy = 1.0


In [32]:
print(confusion_matrix(y_test,y_pred_rf))

[[12  0  0]
 [ 0 13  0]
 [ 0  0  8]]


In [33]:
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(n_estimators=20)
rf_clf.fit(x_train,y_train)

RandomForestClassifier(n_estimators=20)

In [34]:
y_pred_rf = rf_clf.predict(x_test)

In [35]:
print('accuracy =' , accuracy_score(y_test,y_pred_rf))

accuracy = 1.0


In [36]:
print(confusion_matrix(y_test,y_pred_rf))

[[12  0  0]
 [ 0 13  0]
 [ 0  0  8]]


In [39]:
y_pred_rf

array([1, 0, 0, 0, 2, 1, 1, 2, 1, 0, 2, 0, 1, 0, 2, 2, 0, 1, 2, 1, 0, 0,
       2, 0, 2, 1, 1, 1, 1, 0, 0, 1, 1])